allow reward blocking in distribution module
Stride-Labs/cosmos-sdk-old pull request #3
Opened 2022-08-30 22:38 UTC by asalzmann

## Description

Note: This PR isn't nearly as big as it seems! Most of the LOC changed are generated

Stride requires some addresses to be blacklisted, so that they _can_ vote and bond, but _cannot_ accrue staking rewards. These addresses are specified as a parameter. There are two steps to the blacklisting process
1. Scale down rewards for a validator so that the rewards are proportional to the validator's whitelisted stake
2. Only distribute tokens to addresses if they are not blocked

**Scaling down rewards for a validator so that rewards are proportional to the validator's whitelisted stake**
Here, we need to scale down by the proportion of whitelisted stake. Note, at block n, we distribute rewards for block n-1, which was signed by validators finalized in block n-3. See https://github.com/tendermint/tendermint/pull/1815 for more details

To achieve this, we
- Store `BlacklistedPower` and `ValidatorBlacklistedPower` (which indexes validator power by block)
- Index in the `BeginBlocker`
- Add `GetTotalBlacklistedPower ` which returns the total power and blacklisted power for a validator

We construct a map from validator -> blacklisted power for all validators. Using this, we downscale in allocation.go

**Distribute to addresses that are not blocked**

**Only distribute addresses if they are not blocked**
- In `CalculateDelegationRewards` we return 0 coins for 
- In `withdrawDelegationRewards`, we set rewards to 0

Question: @riley-stride why do we need both of these? 

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-09-01 05:06 UTC, riley-stride requested changes
Looking really good! Added comments / suggestions / questions

Wasn't able to meaningfully test the third setup in the PR description **"test assumption that block n+3 is signed by the validator set from block n"**.

Main merge blocker is handling the case where there are no blacklisted delegations

2022-09-01 05:06 UTC, riley-stride commented on proto/cosmos/distribution/v1beta1/distribution.proto
> +  repeated string no_rewards_validator_addresses = 5;
let's scrap this param

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/types/keys.go
> +// GetDelegatorWithdrawAddrKey creates the key for a delegator's withdraw addr.
nit : comment

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/types/params.go
> +	ParamStoreKeyNoRewardsValidatorAddresses = []byte("norewardsvalidatoraddresses")
rm norewardsvalidatoraddresses and that param throughout this file

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/delegation.go
> +	if k.StringInSlice(del.GetDelegatorAddr().String(), blacklistedDelAddrs) {
@asalzmann can you give this a look-over and a quick think on whether there are other places we need to prevent withdrawals by blacklisted delegators?

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/blacklisted_power.go
> +	fmt.Println("b", b)
nit rm comments throughout before we merge

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/blacklisted_power.go
> +// get the delegator withdraw address, defaulting to the delegator address
nit: comment

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/allocation_test.go
> +	blacklistedValidatorRewards := sdk.NewDec(93_000_000).Mul(sdk.NewDec(10).Quo(sdk.NewDec(110))).Add(sdk.NewDec(5_000_000)).RoundInt64()
I like setting the expected amount this way, with clear arithmetic, nice!

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/allocation_test.go
> +// STRIDE TESTS
These make sense. The only other cases I think we might consider testing are redelegations and undelegation by blacklisted validators. Wdyt?

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/allocation_block_helpers.go
> +		return 0, 0
We catch this "error" somewhat by checking that blacklistedPower can't be 0 at the call site. Can we instead return a third value, `error`, and check that at the call site?

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/allocation_block_helpers.go
> +	vals := k.GetAllValidators(ctx)
Seems like we're iterating over all validators. I thought this was previously written in a way that's a bit more efficient bc it only iters over B * V_B where B = blacklistedDelegators and V_B is taintedValidators

Something like this 
```
taintedvals := []
for del in blacklist:
     delegations <- del.delegations
     taintedVals = unique(union(taintedVals, delegations.validators))

blacklistedPowerShareByValidator = map[string]sdk.Dec
for val in taintedVals:
      blacklistedPowerShareByValidator[val] = getBlklistedShare(val)
```
Then when we need the blacklisted power shares by validator, we check inclusion in the map. If included, use its share in the map. If not included the share is 1

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/allocation.go
> +			valWhitelistedPowerShare := sdk.NewDec(1).Sub(blacklistedPowerShareByValidator[valAddr])
if we refactor the getter for `blacklistedPowerShareByValidator`, remember to update code here to check inclusion in map keys or we'll get a nil when indexing into the map

2022-09-01 05:06 UTC, riley-stride commented on x/distribution/keeper/allocation.go
> +	if len(validatorBlacklistedPowers) == 0 {
I think this is a merge blocker. Happy to grab it. Naively you could fork the logic below on this, where the `len(validatorBlacklistedPowers) == 0` case simply runs the original `AllocateTokens` function

2022-09-01 05:07 UTC, riley-stride commented
Some of these suggestions are to self, happy to take them just lmk @asalzmann

2022-09-01 05:12 UTC, riley-stride commented on x/distribution/keeper/allocation_test.go
> +	app.DistrKeeper.AllocateTokens(ctx, 200_000, 200_000, valConsAddr2, votes)
This test fails for me on line 106, does it also fail for you? 
```
allocation_test.go:106
        	Error:      	Not equal: 
        	            	expected: types.DecCoins{types.DecCoin{Denom:"stake", Amount:46.500000000000000000}}
        	            	actual  : types.DecCoins(nil)
```

2022-09-01 12:54 UTC, asalzmann commented on types/address.go
> +	Bech32MainPrefix = "stride"
@riley-stride why this change?

2022-09-01 12:54 UTC, asalzmann commented on types/address.go
> +	Bech32MainPrefix = "stride"
if this is used, how was stride working before this change? 🤔

2022-09-01 12:54 UTC, asalzmann commented on x/distribution/types/keys.go
> +func GetBlacklistedPowerKey(blockHeight string) []byte {
CHECK: why do we need to prefix this with a byte?

2022-09-01 12:54 UTC, asalzmann commented on x/distribution/types/params.go
> +func validateNoRewardsValidatorAddresses(i interface{}) error {
can we get rid of this? @riley-stride

2022-09-01 12:57 UTC, asalzmann commented on x/distribution/types/keys.go
> +// GetDelegatorWithdrawAddrKey creates the key for a delegator's withdraw addr.
done

2022-09-01 12:59 UTC, asalzmann commented on proto/cosmos/distribution/v1beta1/distribution.proto
> +  repeated string no_rewards_validator_addresses = 5;
removed

2022-09-01 12:59 UTC, asalzmann commented on x/distribution/types/params.go
> +	ParamStoreKeyNoRewardsValidatorAddresses = []byte("norewardsvalidatoraddresses")
removed

2022-09-01 12:59 UTC, asalzmann commented on x/distribution/keeper/blacklisted_power.go
> +// get the delegator withdraw address, defaulting to the delegator address
done

2022-09-01 13:00 UTC, asalzmann commented on x/distribution/keeper/blacklisted_power.go
> +	fmt.Println("b", b)
done

2022-09-01 13:00 UTC, asalzmann commented on x/distribution/keeper/allocation_test.go
> +// STRIDE TESTS
Can you sketch out the test you have in mind?

2022-09-01 13:03 UTC, asalzmann commented on x/distribution/types/params.go
> +func validateNoRewardsValidatorAddresses(i interface{}) error {
removed

2022-09-01 13:24 UTC, asalzmann commented on x/distribution/keeper/allocation_block_helpers.go
> +	vals := k.GetAllValidators(ctx)
I refactored this because the efficiency gained was small relatively small
- I'm not sure filtering down to blacklisted validators helps us much - if a blacklisted validator delegates to all validators, this loops over all validators anyway! so the efficiency is the same in that case, and it seems likely that blacklisted stake will be spread over most of the active set
- The loop over all validators adds a loop over ~1000 elements, while B*V_B is likely > 1000 anyway (so it has the same O(n))

and the complexity it introduced was relatively high
- introduces a new concept - "tainted validators"
- must handle edge cases around the map including / not including validators in allocation.go
- need `unionStrSlices`

Given it's unclear how much efficiency we gain here (the iterations are small and we run the code infrequently), but having a bug here is bad, I refactored

2022-09-01 13:24 UTC, asalzmann commented on x/distribution/keeper/allocation.go
> +			valWhitelistedPowerShare := sdk.NewDec(1).Sub(blacklistedPowerShareByValidator[valAddr])
commented above on the refactor, but we should probably check inclusion regardless

2022-09-01 14:28 UTC, asalzmann commented on x/distribution/keeper/allocation_test.go
> +	app.DistrKeeper.AllocateTokens(ctx, 200_000, 200_000, valConsAddr2, votes)
succeeds for me
```
--- PASS: TestCalculateRewardsAfterSlash (0.01s)
```

2022-09-01 14:29 UTC, asalzmann commented on x/distribution/keeper/allocation_test.go
> +	app.DistrKeeper.AllocateTokens(ctx, 200_000, 200_000, valConsAddr2, votes)
can you try re-running it? 🤔

2022-09-01 17:55 UTC, asalzmann commented on x/distribution/keeper/allocation_block_helpers.go
> +		return 0, 0
good call, done

2022-09-01 17:57 UTC, asalzmann commented on x/distribution/keeper/allocation.go
> +	if len(validatorBlacklistedPowers) == 0 {
done

2022-09-01 20:10 UTC, sampocs reviewed
Looks amazing, this is very impressive stuff! Apologies for having no real high level/logical suggestions, but that's probably a good thing!

2022-09-01 20:10 UTC, sampocs commented on x/distribution/types/params.go
> +		CommunityTax:                sdk.NewDecWithPrec(2, 2), // 2%
I wish I knew of this function months ago!

2022-09-01 20:10 UTC, sampocs commented on x/distribution/abci.go
> +		fmt.Println("abci blacklistedPower", blacklistedPower)
Is this supposed to be `fmt.Println` instead of a log?

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation.go
> +		// k.Logger(ctx).Info(fmt.Sprintf("...%s", valAddr))
nit, looks like there's some commented debugging lines. Either uncomment or remove

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_block_helpers.go
> +			// something went wrong
should we log something here?

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_block_helpers.go
> +func (k Keeper) GetTotalBlacklistedPower(ctx sdk.Context, valAddr string) (int64, int64) {
named return params?

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_block_helpers.go
> +func (k Keeper) GetValsBlacklistedPowerShare(ctx sdk.Context) (totalBlacklistedPower sdk.Dec, blacklistedPowerShareByValidator []types.ValidatorBlacklistedPower) {
I think the early confusion is most definitely on me for it just taking a while to wrap my head around this, so feel free to shut this down. That said, I'm wondering if we could name these a little more clearly. Here are the four similarly named functions:

```
GetBlacklistedPower                           (blockNum) -> [blacklist power object]
GetBlacklistedPowerShareByValidator (list of val powers) -> [map of val -> val blacklisted power share]
GetValsBlacklistedPowerShare                          () -> [totalpower, list of blacklisted power shares for each val]
GetTotalBlacklistedPower                           (val) -> [totalpower, blacklisted power]
```

what do you think about:
```
GetBlacklistedPower // (unchanged) assuming we should keep this name since its a basic keeper function
GetBlacklistedPowerShareByValidator → GetValidatorToBlacklistedPowerShareMap
GetValsBlacklistedPowerShare        → GetAllValidatorsBlacklistedPowerShares
GetTotalBlacklistedPower            → GetValidatorTotalBlacklistedPower
```

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation.go
> +		k.Logger(ctx).Error(fmt.Sprintf("no blacklisted power found for block height%s", height))
```suggestion
		k.Logger(ctx).Error(fmt.Sprintf("no blacklisted power found for block height %s", height))
```

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation.go
> +		totalWhitelistedPowerShare = sdk.NewDec(1).Sub(totalBlacklistedPower.Quo(sdk.NewDec(totalPreviousPower)))
just double checking - does this `totalPreviousPower` line up with block n - 3? Does it make sense to just add this value to the BlacklistedPower struct?

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation.go
> +		// k.Logger(ctx).Info(fmt.Sprintf("...%s", valAddr))
nit: uncomment or remove

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation.go
> +		powerFraction = sdk.NewDec(validatorPowerAdj).QuoTruncate(sdk.NewDec(totalWhitelistedPower))
I might be off with the terminology here, but if not:
```suggestion
		validatorWhitelistedPower := sdk.NewDec(vote.Validator.Power).Mul(valWhitelistedPowerShare).RoundInt64()
		validatorWhitelistedPowerShare = sdk.NewDec(validatorWhitelistedPower).QuoTruncate(sdk.NewDec(totalWhitelistedPower))
```

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation.go
> +		var powerFraction sdk.Dec
does this need to be declared here?

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/delegation.go
> +		}
```suggestion
		denom, err := sdk.GetBaseDenom()
		if err != nil {
		    return nil, err
		}
		
		newRewardsRaw := sdk.NewDecCoins(sdk.NewDecCoin(denom, sdk.ZeroInt()))
		k.Logger(ctx).Info(fmt.Sprintf("BLACKLIST_DELEGATION: rewards, non-blacklisted: %v blacklisted: %v", rewardsRaw, newRewardsRaw))
		rewardsRaw = newRewardsRaw
		
```

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_test.go
> +	fmt.Println("found: ", found)
I assume you guys are still debugging these, but just remove when you're done

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_test.go
> +	require.True(t, app.DistrKeeper.GetValidatorAccumulatedCommission(ctx, valAddrs[0]).Commission.IsZero())
apologies, I'm a little confused on this.

I thought commission was set to 0 - why is it shown here as 5% and then confirmed later that its 0?

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_test.go
> +	require.Equal(t, sdk.DecCoins{{Denom: sdk.DefaultBondDenom, Amount: sdk.NewDec(93_000_000)}}, app.DistrKeeper.GetValidatorCurrentRewards(ctx, valAddrs[0]).Rewards)
Just food for though, since there's a lot going on this test, it might make sense to define expectations at the top along side the initialized values so you can quickly get a summary of the test.
E.g.
```
	startingAcctBalance := sdk.NewInt(5_000_000_000)
	amtToSelfBond := sdk.NewInt(100_000_000)
	sumPreviousPrecommitPower, totalPreviousPower := int64(200), int64(200)
	feesAmt := sdk.NewInt(100_000_000)

        expectedVal1StakingRewards := sdk.DecCoins{{Denom: sdk.DefaultBondDenom, Amount: sdk.NewDec(93_000_000)}}
        expectedVal2StakingRewards := sdk.DecCoins{{Denom: sdk.DefaultBondDenom, Amount: sdk.NewDec(5_000_000)}}
      ...
```

That said, the documentation is also super helpful here, so there's a chance it would actually become more confusing if variables were used instead. I'll defer to y'all!

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_test.go
> +	fmt.Println("found: ", found)
same with other tests

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_test.go
> +	require.Equal(t, sdk.DecCoins{{Denom: sdk.DefaultBondDenom, Amount: sdk.NewDec(93_000_000)}}, app.DistrKeeper.GetValidatorCurrentRewards(ctx, valAddrs[0]).Rewards)
doesn't the first validator have blacklisted delegators here? These results look identical to the first test

2022-09-01 20:10 UTC, sampocs commented on x/distribution/keeper/allocation_test.go
> +
Up to you guys if you think this is two big of a facelift, but I think these tests would be a lot more digestible if you added a setup function and and validation function. It looks they both could be parameterized easy enough to accommodate these tests. I think ideally the tests would read:
```
initialValues := ...
expectedValues := ...

setup()

validate(expectedValues) // obviously use a better function name here
```

2022-09-01 20:38 UTC, asalzmann commented on x/distribution/keeper/delegation.go
> +	if k.StringInSlice(del.GetDelegatorAddr().String(), blacklistedDelAddrs) {
Looking at the distribution module now

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/types/keys.go
> +func GetBlacklistedPowerKey(blockHeight string) []byte {
All indexes should have a prefix s.t. you can effectively iterate and also not have accidental key overwrites.

Also, I would consider not using a string for height which allows you to not have to string format. Instead, use `sdk.Uint64ToBigEndian`

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/types/params.go
> +	return nil
```suggestion
	addrs, ok := i.([]string)
	if !ok {
		return fmt.Errorf("invalid parameter type: %T", i)
	}

	for _, addr := addrs {
		_, err := sdk.AccAddressFromBech32(addr)
		if err != nil {
			return fmt.Errorf("could not parse address!: %s", addr)
		}
	}	
	
	return nil
```

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/delegation.go
> +		}
This is cleaner IMO 👍

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/allocation_block_helpers.go
> +func (k Keeper) StringInSlice(a string, list []string) bool {
nit: no need to define this on the keeper type.

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/allocation_block_helpers.go
> +func (k Keeper) GetAllValidators(ctx sdk.Context) (validatorAddresses []string) {
```suggestion
func (k Keeper) GetAllBondedValidators(ctx sdk.Context) (validatorAddresses []string) {
```

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/allocation_block_helpers.go
> +			// Only consider active validators; inactive validators can't have signed the last block (CHECK ASSUMPTION)
This is correct

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/allocation_block_helpers.go
> +	valBlacklistedPower := int64(0)
```suggestion
	var valBlacklistedPower int64
```

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/allocation_block_helpers.go
> +			// TODO: why does TokensFromShares return a dec, when all tokens are ints? I truncate manually here -- is that safe?
This is because the shares are fractional (must be to handle slashing), so when you multiply shares * total tokens, we let the caller decide how to deal with the value, typically by just truncating.

2022-09-13 09:20 UTC, alexanderbez commented on x/distribution/keeper/allocation_block_helpers.go
> +			// TODO: why does TokensFromShares return a dec, when all tokens are ints? I truncate manually here -- is that safe?
You can just call `TokensFromSharesTruncated` IMO

2022-11-04 00:02 UTC, closed without merging